### ISSUE TITLE
Global loading variable prevents loading styles on 2nd opened file

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [emanuelen5/emanuelen5.github.io#13]
Ran into another small issue:

When opening a buffer things work fine, but after doing a `:e`, or opening another markdown file, highlighting doesn't work anymore. This seems to be caused by the global variable being set on first load, preventing applying the style when opening new files.

Removing the if statement worked just fine, but I'm no expert on vimscript so there may be a better way to do this? (You probably had a reason for adding this.) Otherwise happy to create a PR again ;)

**Comment by emanuelen5** [comment]
Wrong repo. You probably wanted this one: https://github.com/emanuelen5/vim-jekyll-syntax :)
Of course you may open another pull request if you manage to solve the issue. I'd be happy if you do.
